# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.0"
slug: ispyagentdvr
description: Example add-on
url: "https://github.com/PauloFerreira25/ispyagentdvr-homeassistant/tree/main/ispyagentdvr"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-ispyagentdvr"
